services:
  postgres:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shops
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  scala-app:
    build:
      context: project
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - ~/.sbt:/root/.sbt
      - ~/.ivy2:/root/.ivy2
    working_dir: /app
    command: run
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/shops
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: